Remove youtube-play (superseeded by mpv plugin) and using yt-dlp as a fallback

diff --git a/plugins/internet/functions/youtube b/plugins/internet/functions/youtube
--- a/plugins/internet/functions/youtube
+++ b/plugins/internet/functions/youtube
@@ -1,7 +1,10 @@
-local YC="${YOUTUBE_COOKIES:-"${HOME}/.ytdl"}"
-local -a PIECES; PIECES=(${(f)"$(youtube-dl --cookies="${YC}" -o '%(title)s.%(ext)s' --get-filename -g "${1}")"})
-shift
-set -- "$@" --load-cookies "${YC}" -O "${PIECES[2]}" "${PIECES[1]}"
-wget "$@"
+: ${1?"USAGE: youtube <url> [output template]"}
+
+if ! is-alias ytdl; then
+  echo 'youtube-dl or yt-dlp not found' >&2
+  return 1
+fi
+
+ytdl --cookies="${YOUTUBE_COOKIES:-"${HOME}/.ytdl"}" -o "${2:-"%(title)s.%(ext)s"}" "${1}"
 
 # vim: ft=zsh sts=2 ts=2 sw=2 et fdm=marker fmr={{{,}}}
diff --git a/plugins/internet/functions/youtube-mp3 b/plugins/internet/functions/youtube-mp3
--- a/plugins/internet/functions/youtube-mp3
+++ b/plugins/internet/functions/youtube-mp3
@@ -1,3 +1,15 @@
-command youtube-dl -i -f bestaudio -o '%(title)s.%(ext)s' -x --audio-format mp3 --audio-quality 0 "$@"
+: ${1?"USAGE: youtube-mp3 <url> [output template]"}
+
+if ! is-alias ytdl; then
+  echo 'youtube-dl or yt-dlp not found' >&2
+  return 1
+fi
+
+ytdl --cookies="${YOUTUBE_COOKIES:-"${HOME}/.ytdl"}" \
+  -i -f bestaudio \
+  -o "${2:-"%(title)s.%(ext)s"}" \
+  -x --audio-format mp3 \
+  --audio-quality 0 \
+  "${1}"
 
 # vim: ft=zsh sts=2 ts=2 sw=2 et fdm=marker fmr={{{,}}}
